from config.constants import (
    SABORES_NORMALES,
    SABORES_CLIENTES,
    TAMANOS_NORMALES,
    TAMANOS_CLIENTES,
    SUCURSALES,
    SUCURSALES_FILTRO,
    TAMANOS
)

__all__ = [
    'SABORES_NORMALES',
    'SABORES_CLIENTES',
    'TAMANOS_NORMALES',
    'TAMANOS_CLIENTES',
    'SUCURSALES',
    'SUCURSALES_FILTRO',
    'TAMANOS'
]
